trigger:
  branches:
    include:
      - release/*
pr: none

pool:
  vmImage: ubuntu-18.04

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - bash: git rev-parse --short HEAD
